/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-03 02:07:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.consult;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class csCenter_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/ezen_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1687741574536L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <script src=\"https://kit.fontawesome.com/e927512ef5.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<!-- CSS only -->\r\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65\" crossorigin=\"anonymous\">\r\n");
      out.write("<!-- JavaScript Bundle with Popper -->\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,0,200\" />\r\n");
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/consult/csCenter.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/resources/css/HF.css\">\r\n");
      out.write("    <title>이용안내</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("    <!-- 헤더 -->\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"container\" style=\"min-width: 100vw !important;\">\r\n");
      out.write("			<div class=\"header\">\r\n");
      out.write("				<a href=\"/home\"> \r\n");
      out.write("					<div class=\"logo-title\">\r\n");
      out.write("						<img src=\"/resources/img/logo2.svg\" alt=\"\">\r\n");
      out.write("						<h1 class=\"title\" style=\"color: #555; margin: 0\">OK Rental</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				<!-- 우측에 위치 -->\r\n");
      out.write("				<div class=\"header-right\">\r\n");
      out.write("					<div class=\"info\">\r\n");
      out.write("						<i class=\"fa-sharp fa-solid fa-user fa-xl\" style=\"color: #555;\"\r\n");
      out.write("							onclick=\"toggleTooltip();\"></i>\r\n");
      out.write("						<div id=\"tooltip\" class=\"speech-bubble\">\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<!-- 230710 서치 -->\r\n");
      out.write("					<div class=\"search\">\r\n");
      out.write("						<span id=\"search\"> <i\r\n");
      out.write("							class=\"fa-solid fa-magnifying-glass fa-xl\" style=\"color: #555;\"></i>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"myOverlay\" class=\"overlay\">\r\n");
      out.write("			<span class=\"closebtn\" onclick=\"closeSearch()\" title=\"Close Overlay\">×</span>\r\n");
      out.write("			<div class=\"overlay-content\">\r\n");
      out.write("				<form action=\"/product/search\" method=\"get\">\r\n");
      out.write("					<div class=\"search-container\">\r\n");
      out.write("						<h1 style=\"color: white;\">Quickly Search Site</h1>\r\n");
      out.write("						<div class=\"search-box\">							\r\n");
      out.write("							<input type=\"text\" placeholder=\"Search..\" name=\"search\"\r\n");
      out.write("								class=\"search-input\">\r\n");
      out.write("							<button class=\"search-box-btn\" type=\"submit\" style=\"color: #555;\">Search</button>					\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("				<div class=\"quickly\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\r\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=다이슨\"> dyson</a></li>\r\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\r\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=엘지\"> lg </a></li>\r\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\r\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=쿠쿠\"> cuckoo </a></li>\r\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\r\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=코웨이\"> coway </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"blurryPart\" class=\"blurry-part\"></div>\r\n");
      out.write("		<!-- 230710 서치 -->\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- 헤더시마이 -->\r\n");
      out.write("    <!-- 분리 -->\r\n");
      out.write("     <div id=\"main\">\r\n");
      out.write("      <h1>이용안내</h1>\r\n");
      out.write("      <div id=\"sBox\">\r\n");
      out.write("        <div id=\"leftBox\">\r\n");
      out.write("          <span class=\"material-symbols-outlined\" id=\"telephone\">\r\n");
      out.write("            phone_in_talk\r\n");
      out.write("          </span>\r\n");
      out.write("          <h3>고객센터</h3>\r\n");
      out.write("          <p>전화문의 : 1544-1234</p>\r\n");
      out.write("          <p>이용시간 : 평일 09:00 ~ 18:00 / 토요일 09:00 ~ 17:00</p>\r\n");
      out.write("          <p>(점심시간 : 12:00 ~ 13:00 / 일요일, 공휴일 휴무)</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"rightBox\">\r\n");
      out.write("          <span class=\"material-symbols-outlined\" id=\"pen\"> stylus </span>\r\n");
      out.write("          <h3>1:1문의</h3>\r\n");
      out.write("          <button type=\"button\" id=\"ask\">문의하기</button>\r\n");
      out.write("          <p>평일 오후 5시 이후 문의는 당일 답변이 어려울 수 있습니다.</p>\r\n");
      out.write("          <p>\r\n");
      out.write("            토, 일요일 / 공휴일 문의는 운영시간 내 순차적으로 답변 드리겠습니다.\r\n");
      out.write("          </p>\r\n");
      out.write("          <p>(점심시간 : 12:00 ~ 13:00 / 일요일, 공휴일 휴무)</p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"list\">\r\n");
      out.write("        <a href=\"#\" id=\"smallBox1\">TV</a>\r\n");
      out.write("        <a href=\"#\" id=\"smallBox2\">자주 묻는 질문</a>\r\n");
      out.write("        <a href=\"#\" id=\"smallBox3\">렌탈</a>\r\n");
      out.write("        <a href=\"#\" id=\"smallBox4\">전화/기타</a>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div id=\"tvBox\" style=\"display: none\">\r\n");
      out.write("        <hr>\r\n");
      out.write("          <h1>셀프해결 가이드</h1>\r\n");
      out.write("          <p>TV가 안나오고 \"방송신호가 없습니다\" 메시지가 보여요</p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <span style=\"color: red\">TV가 안나오고 \"방송신호가 없습니다\"메시지가 뜰 경우, 아래 순서로 확인하시면 해결할 수 있습니다</span><br>\r\n");
      out.write("            <span style=\"color: red\">1. 셋톱박스 전원상태 확인</span><br>\r\n");
      out.write("            <span style=\"color: red\">2. TV와 셋톱박스의 연결선 확인</span><br>\r\n");
      out.write("            <span style=\"color: red\">3. 셋톱박스 리모컨으로 외부입력 전환</span><br>\r\n");
      out.write("            <span style=\"color: red\">현재 사용하시는 리모컨 이미지를 누르시면, 자세한 안내 페이지로 이동합니다.</span><br>\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"remoteBox\">\r\n");
      out.write("          <a class=\"remote\">\r\n");
      out.write("          <img src=\"/resources/img/리모컨1.png\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"remote\">\r\n");
      out.write("          <img src=\"/resources/img/리모컨2.png\">\r\n");
      out.write("          </a>\r\n");
      out.write("          <a class=\"remote\">\r\n");
      out.write("          <img src=\"/resources/img/리모컨3.png\">\r\n");
      out.write("          </a>\r\n");
      out.write("          </div>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       \r\n");
      out.write("    <div id=\"internetBox\" style=\"display: none\">\r\n");
      out.write("    <hr>\r\n");
      out.write("    <h1>자주 묻는 질문</h1>\r\n");
      out.write("      <div class=\"accordion accordion-flush\" id=\"accordionFlushExample\">\r\n");
      out.write("     <div class=\"accordion-item\">\r\n");
      out.write("    <h2 class=\"accordion-header\" id=\"flush-headingOne\">\r\n");
      out.write("      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseOne\" aria-expanded=\"false\" aria-controls=\"flush-collapseOne\">\r\n");
      out.write("        <strong>결제 계좌 및 결제 방법을 변경하려면 어떻게 해야 하나요?</strong>\r\n");
      out.write("      </button>\r\n");
      out.write("    </h2>\r\n");
      out.write("    <div id=\"flush-collapseOne\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingOne\" data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("      <div class=\"accordion-body\"><span>＊ 자동이체 계좌를 변경할 경우 고객센터를 통해 변경가능합니다.</span><br>\r\n");
      out.write("            <span>＊ 카드결제변경의 경우 고객센터 또는 오케이렌탈 홈페이지 >> 렌탈서비스 신청 >> 결제카드변경에서 변경 가능합니다.</span></div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"accordion-item\">\r\n");
      out.write("    <h2 class=\"accordion-header\" id=\"flush-headingTwo\">\r\n");
      out.write("      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseTwo\" aria-expanded=\"false\" aria-controls=\"flush-collapseTwo\">\r\n");
      out.write("        <strong>설치점 또는 관리점 연락처를 어떻게 확인 가능한가요?</strong><br>\r\n");
      out.write("      </button>\r\n");
      out.write("    </h2>\r\n");
      out.write("    <div id=\"flush-collapseTwo\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingTwo\" data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("      <div class=\"accordion-body\"><span>＊ 설치점/관리점은 고객센터를 통해 연락처 확인 가능합니다.</span><br>\r\n");
      out.write("            <span>＊ 또는 오케이렌탈 홈페이지 >> 렌탈서비스 신청 >> 설치점/관리점 연락처 조회에서 확인가능합니다.</span></div>\r\n");
      out.write("  </div>\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"accordion-item\">\r\n");
      out.write("    <h2 class=\"accordion-header\" id=\"flush-headingThree\">\r\n");
      out.write("      <button class=\"accordion-button collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#flush-collapseThree\" aria-expanded=\"false\" aria-controls=\"flush-collapseThree\">\r\n");
      out.write("        <strong>이전 설치 접수는 어떻게 해야 하나요?</strong><br>\r\n");
      out.write("      </button>\r\n");
      out.write("    </h2>\r\n");
      out.write("    <div id=\"flush-collapseThree\" class=\"accordion-collapse collapse\" aria-labelledby=\"flush-headingThree\" data-bs-parent=\"#accordionFlushExample\">\r\n");
      out.write("      <div class=\"accordion-body\"> <span>＊ 이전설치 접수할경우 고객센터를 통해 접수 가능합니다.</span><br>\r\n");
      out.write("            <span>＊ 또는 오케이렌탈 홈페이지 >> 렌탈서비스 신청 >> 이전설치 신청/조회에서 접수가능합니다</span></div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("       </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("                 </div>\r\n");
      out.write("                 \r\n");
      out.write("     <div id=\"rentalBox\" style=\"display: none\">\r\n");
      out.write("        <hr>\r\n");
      out.write("          <h1>셀프해결 가이드</h1>\r\n");
      out.write("          <p>오케이렌탈 AS는 어떻게 진행되나요?</p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <strong style=\"color: red\">오케이렌탈 제품의 A/S는 기본적으로 각 제조사별 품질 보장 기간에 의거해 제조사 A/S센터를 통해 무상 A/S 서비스가 진행됩니다. </strong><br>\r\n");
      out.write("            <span>다만, 개인가입고객들은 제품별 청약내용에 따라 당사 계약체결 시점 후 13~36개월차까지 LG헬로비전을 통해 공급사 유상수리 후 </span><br>\r\n");
      out.write("            <span>수리내역과 영수증, 고장수리 보험 신청서 (당사 청약 명의자)를 제출하시면 기준에 의해 수리비용을 보상 받을 수 있습니다.</span><br>\r\n");
      out.write("            <span>(단, 고객 과실이나 천재지변에 의한 A/S는 공급사 정책에 따라 유상수리입니다)</span><br>\r\n");
      out.write("          </p><br>\r\n");
      out.write("          <p>\r\n");
      out.write("             <span>■ 대상상품 : 일부 상품군 (품목확인은 렌탈전담센터 1855-1020 문의)</span><br>\r\n");
      out.write("             <span>■ 보험혜택 : 1회 한도 50만원, 연간 한도 200만원 (회선당)</span><br>\r\n");
      out.write("          </p><br>\r\n");
      out.write("          <p>\r\n");
      out.write("             <span>※ 청약 제품별 고장수리비 적용 여부가 다르니 확인 부탁드립니다.</span><br>\r\n");
      out.write("          </p><br>\r\n");
      out.write("          <p>\r\n");
      out.write("             <span>■ 19년 8/29이후 가입자 대상 신청절차 : ①대상상품 확인(홈페이지) → ②가전사 유상수리 진행 → ③판정서 및 영수증 구비 → </span><br>\r\n");
      out.write("             <span>    ④렌탈전담센터 전화(1855-1020) → ⑤납부서류 제출 → ⑥보상처리(심사완료 후 최대 30일 이내 입금 완료</span><br>\r\n");
      out.write("             <span>■ 19년 8/28이전 가입자 대상 신청절차 : ①대상상품 확인(홈페이지) → ②가전사 유상수리 진행 → ③판정서 및 영수증 구비 → </span><br>\r\n");
      out.write("             <span>    ④AIG손해보험 전화(1588-1794) → ⑤납부서류 제출 → ⑥보상처리(심사완료 후 최대 30일 이내 입금 완료</span><br>\r\n");
      out.write("          </p><br>\r\n");
      out.write("       </div>\r\n");
      out.write("       \r\n");
      out.write("       <div id=\"telBox\" style=\"display: none\">\r\n");
      out.write("        <hr>\r\n");
      out.write("          <h1>셀프해결 가이드</h1>\r\n");
      out.write("          <p>통화가 끊기거나 잡음이 들리는 경우</p>\r\n");
      out.write("          <p>\r\n");
      out.write("            <span style=\"color: red\">01 전화기의 무선신호 속도를 측정해보세요.</span><br>\r\n");
      out.write("            <span>전화기 화면 상단에 그림과 같이 통화불가 표시가 계속 된다면 무선랜 재설정을 통해 간단하게 해결이 가능합니다.</span><br>\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"remoteBox\">\r\n");
      out.write("          <a class=\"remote\">\r\n");
      out.write("          <img src=\"/resources/img/전화1.png\" class=\"remoteImg\">\r\n");
      out.write("          </a>\r\n");
      out.write("          </div>\r\n");
      out.write("          <p>\r\n");
      out.write("            <span style=\"color: red\">02 공유기 위치 및 상태를 확인해보세요.</span><br>\r\n");
      out.write("            <span>※ 램프에 문제가 있다면 공유기 전원을 뽑았다가 다시 꽂아보세요.</span><br>\r\n");
      out.write("          </p>\r\n");
      out.write("          <div class=\"remoteBox\">\r\n");
      out.write("          <a class=\"remote\">\r\n");
      out.write("          <img src=\"/resources/img/전화2.png\" class=\"remoteImg\">\r\n");
      out.write("          </a>\r\n");
      out.write("          </div>\r\n");
      out.write("       </div>\r\n");
      out.write("    <script src=\"/resources/js/HF.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"/resources/js/consult/csCenter.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		var navBar = document.getElementById('nav-bar');\r\n");
      out.write("		var navBtn = document.getElementById('nav-btn');\r\n");
      out.write("\r\n");
      out.write("		navBtn.addEventListener('mouseenter', function() {\r\n");
      out.write("			navBar.style.width = '300px';\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		navBar.addEventListener('mouseleave', function() {\r\n");
      out.write("			navBar.style.width = '0';\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/consult/csCenter.jsp(45,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<a href=\"/user/signup\">회원가입</a>\r\n");
          out.write("								<br>\r\n");
          out.write("								<a href=\"/user/login\">로그인</a>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/consult/csCenter.jsp(50,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<a href=\"/user/modify\">회원정보수정</a>\r\n");
          out.write("								<br>\r\n");
          out.write("								<a href=\"/user/logout\">로그아웃</a>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
