/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-03 02:07:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.consult;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/ezen_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1687741574536L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<title>상담 신청</title>\n");
      out.write("<script src=\"https://kit.fontawesome.com/e927512ef5.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\n");
      out.write("<link\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap\"\n");
      out.write("	rel=\"stylesheet\">\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/consult/consult.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/HF.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- 헤더 -->\n");
      out.write("	<header style=\"width: 100%;\">\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"header\">\n");
      out.write("				<a href=\"/home\"> \n");
      out.write("					<div class=\"logo-title\">\n");
      out.write("						<img src=\"/resources/img/logo2.svg\" alt=\"\">\n");
      out.write("						<h1 class=\"title\" style=\"color: #555;\">OK Rental</h1>\n");
      out.write("					</div>\n");
      out.write("				</a>\n");
      out.write("				<!-- 우측에 위치 -->\n");
      out.write("				<div class=\"header-right\">\n");
      out.write("					<div class=\"info\">\n");
      out.write("						<i class=\"fa-sharp fa-solid fa-user fa-xl\" style=\"color: #555;\"\n");
      out.write("							onclick=\"toggleTooltip();\"></i>\n");
      out.write("						<div id=\"tooltip\" class=\"speech-bubble\">\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("							<!-- 로그인해야 수정 삭제가 보이게 -->\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- 230710 서치 -->\n");
      out.write("					<div class=\"search\">\n");
      out.write("						<span id=\"search\"> <i\n");
      out.write("							class=\"fa-solid fa-magnifying-glass fa-xl\" style=\"color: #555;\"></i>\n");
      out.write("						</span>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div id=\"myOverlay\" class=\"overlay\">\n");
      out.write("			<span class=\"closebtn\" onclick=\"closeSearch()\" title=\"Close Overlay\">×</span>\n");
      out.write("			<div class=\"overlay-content\">\n");
      out.write("				<form action=\"/product/search\" method=\"get\" style=\"margin: 0 auto;\">\n");
      out.write("					<div class=\"search-container\">\n");
      out.write("						<h1 style=\"color: white; text-align: center;\">Quickly Search Site</h1>							\n");
      out.write("						<div class=\"search-box\" style=\"text-align: center;\">\n");
      out.write("							<input type=\"text\" placeholder=\"Search..\" name=\"search\"\n");
      out.write("									class=\"search-input\">\n");
      out.write("							<button type=\"submit\" style=\"color: #555;\">Search</button>\n");
      out.write("						</div>	\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("				<div class=\"quickly\">\n");
      out.write("					<ul>\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=다이슨\"> dyson</a></li>\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=엘지\"> lg </a></li>\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=쿠쿠\"> cuckoo </a></li>\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=코웨이\"> coway </a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div id=\"blurryPart\" class=\"blurry-part\"></div>\n");
      out.write("		<!-- 230710 서치 -->\n");
      out.write("		\n");
      out.write("\n");
      out.write("\n");
      out.write("	</header>\n");
      out.write("	<!-- 헤더시마이 -->\n");
      out.write("	<div>\n");
      out.write("		<h1 style=\"margin-top: 88px;\">상담 신청</h1>\n");
      out.write("	</div>\n");
      out.write("	<form style=\"padding: 20px;\" action=\"/consult/register\" method=\"post\" id=\"registerForm\">\n");
      out.write("		<table>\n");
      out.write("			<tbody>\n");
      out.write("				<tr>\n");
      out.write("					<th>아이디 <span data-tooltip=\"필수항목\"><i\n");
      out.write("							class=\"fa-solid fa-circle-exclamation fa-2xs\"\n");
      out.write("							style=\"color: #ff0000;\"></i></span>\n");
      out.write("					</th>\n");
      out.write("					<td><input type=\"text\" name=\"csid\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\"></td>\n");
      out.write("				</tr>\n");
      out.write("				<!-- 추가 -->\n");
      out.write("				<tr>\n");
      out.write("					<th>이름 <span data-tooltip=\"필수항목\"><i\n");
      out.write("							class=\"fa-solid fa-circle-exclamation fa-2xs\"\n");
      out.write("							style=\"color: #ff0000;\"></i></span>\n");
      out.write("					</th>\n");
      out.write("					<td><input type=\"text\" name=\"csname\">\n");
      out.write("						<p id=\"csnameError\" style=\"color: red; display: none;\">이름을 입력해주세요.</p>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<th>핸드폰번호 <span data-tooltip=\"필수항목\"><i\n");
      out.write("							class=\"fa-solid fa-circle-exclamation fa-2xs\"\n");
      out.write("							style=\"color: #ff0000;\"></i></span>\n");
      out.write("					</th>\n");
      out.write("					<td><input type=\"text\" name=\"cstel\">\n");
      out.write("						<p id=\"cstelError\" style=\"color: red; display: none;\">핸드폰번호를 입력해주세요.</p>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<!-- 추가 -->\n");
      out.write("				<tr>\n");
      out.write("					<th>상품이름 <span data-tooltip=\"필수항목\"><i\n");
      out.write("							class=\"fa-solid fa-circle-exclamation fa-2xs\"\n");
      out.write("							style=\"color: #ff0000;\"></i></span>\n");
      out.write("					</th>\n");
      out.write("					<td>\n");
      out.write("						<select name=\"cstype\" id=\"\">\n");
      out.write("								<option value=\"\" selected>선택</option>\n");
      out.write("								<option value=\"정수기\">정수기</option>\n");
      out.write("								<option value=\"공기청정기\">공기청정기</option>\n");
      out.write("								<option value=\"제습기\">제습기</option>\n");
      out.write("								<option value=\"에어컨\">에어컨</option>\n");
      out.write("								<option value=\"텔레비전\">텔레비전</option>\n");
      out.write("						</select>\n");
      out.write("						<p id=\"cstypeError\" style=\"color: red; display: none;\">상품이름을 입력해주세요.</p>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("				<tr>\n");
      out.write("					<th>상담내용</th>\n");
      out.write("					<td><textarea name=\"cscontent\" id=\"\" cols=\"30\" rows=\"10\"></textarea>\n");
      out.write("						<p id=\"cscontentError\" style=\"color: red; display: none;\">상담내용을 입력해주세요.</p>\n");
      out.write("					</td>\n");
      out.write("				</tr>\n");
      out.write("			</tbody>\n");
      out.write("		</table>\n");
      out.write("		<div class=\"subtitle\">개인정보의 수집 및 이용에 대한 안내</div>\n");
      out.write("		개인정보의 처리 <span data-tooltip=\"필수항목\"><i class=\"fa-solid fa-circle-exclamation fa-2xs\"\n");
      out.write("			style=\"color: #ff0000;\"></i></span> <span id=\"privacy-policy\"\n");
      out.write("			style=\"cursor: pointer;\" class=\"detail\">자세히보기</span>\n");
      out.write("		<!-- ***************************************************************************************************************************************************************************************************** -->\n");
      out.write("		<div id=\"policy-modal\" class=\"modal\">\n");
      out.write("			<span id=\"close-button-policy\" class=\"close\">&times;</span>\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<p>※ \"개인정보\"란 살아 있는 개인에 관한 정보로서 다음의 어느 하나에 해당하는 정보를 말합니다(「개인정보\n");
      out.write("					보호법」 제2조제1호). 1. 성명, 주민등록번호 및 영상 등을 통하여 개인을 알아볼 수 있는 정보 2. 해당\n");
      out.write("					정보만으로는 특정 개인을 알아볼 수 없더라도 다른 정보와 쉽게 결합하여 알아볼 수 있는 정보(이 경우 쉽게 결합할 수\n");
      out.write("					있는지 여부는 다른 정보의 입수 가능성 등 개인을 알아보는 데 소요되는 시간, 비용, 기술 등을 합리적으로 고려하여야\n");
      out.write("					함) 3. 가명처리함으로써 원래의 상태로 복원하기 위한 추가 정보의 사용·결합 없이는 특정 개인을 알아볼 수 없는 정보\n");
      out.write("					※ \"가명처리\"란 개인정보의 일부를 삭제하거나 일부 또는 전부를 대체하는 등의 방법으로 추가 정보가 없이는 특정 개인을\n");
      out.write("					알아볼 수 없도록 처리하는 것을 말합니다((「개인정보 보호법」 제2조제1호의2).</p>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		개인정보의 수집·이용 방법 <span data-tooltip=\"필수항목\"><i class=\"fa-solid fa-circle-exclamation fa-2xs\"\n");
      out.write("			style=\"color: #ff0000;\"></i></span> <span id=\"privacy-policy1\"\n");
      out.write("			style=\"cursor: pointer;\" class=\"detail\">자세히보기</span>\n");
      out.write("\n");
      out.write("		<div id=\"policy-modal1\" class=\"modal\">\n");
      out.write("			<span id=\"close-button-policy1\" class=\"close\">&times;</span>\n");
      out.write("			<div class=\"modal-content\">\n");
      out.write("				<p>개인정보의 수집·이용 개인정보처리자\n");
      out.write("				※ \"개인정보\"란 살아 있는 개인에 관한 정보로서 다음의 어느 하나에 해당하는 정보를 말합니다(「개인정보\n");
      out.write("					보호법」 제2조제1호). 1. 성명, 주민등록번호 및 영상 등을 통하여 개인을 알아볼 수 있는 정보 2. 해당\n");
      out.write("					정보만으로는 특정 개인을 알아볼 수 없더라도 다른 정보와 쉽게 결합하여 알아볼 수 있는 정보(이 경우 쉽게 결합할 수\n");
      out.write("					있는지 여부는 다른 정보의 입수 가능성 등 개인을 알아보는 데 소요되는 시간, 비용, 기술 등을 합리적으로 고려하여야\n");
      out.write("					함) 3. 가명처리함으로써 원래의 상태로 복원하기 위한 추가 정보의 사용·결합 없이는 특정 개인을 알아볼 수 없는 정보\n");
      out.write("					※ \"가명처리\"란 개인정보의 일부를 삭제하거나 일부 또는 전부를 대체하는 등의 방법으로 추가 정보가 없이는 특정 개인을\n");
      out.write("					알아볼 수 없도록 처리하는 것을 말합니다((「개인정보 보호법」 제2조제1호의2).</p>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div>\n");
      out.write("			<input type=\"checkbox\">상담진행을 위해 개인정보 수집 및 이용에 동의 합니다.\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<button onclick=\"validateButton(event)\" type=\"submit\"  style=\"margin-bottom: 108px;\">상담신청</button>\n");
      out.write("	</form>\n");
      out.write("		<!-- 푸터 -->\n");
      out.write("	<footer>\n");
      out.write("		<div class=\"footer\">\n");
      out.write("			<div class=\"ft-logo\">\n");
      out.write("				<img src=\"/resources/img/images.png\" alt=\"\" width=\"50px\"\n");
      out.write("					height=\"50px\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"footinfo\">\n");
      out.write("				<span><h6>©2023 Ok RENTAL. All Rights Reserved.</h6></span> <span><h6>RETURN\n");
      out.write("						POLICY</h6></span> <span><h6>TERMS & LEGAL</h6></span> <span><h6>PRIVACY\n");
      out.write("						NOTICE</h6></span>\n");
      out.write("			</div>\n");
      out.write("			<div class=\"footsns\">\n");
      out.write("				<a href=\"https://www.facebook.com/login/?locale=ko_KR\"><i\n");
      out.write("					class=\"fa-brands fa-facebook\" style=\"color: #000000;\"></i></a> <a\n");
      out.write("					href=\"https://twitter.com/i/flow/login?input_flow_data=%7B%22requested_variant%22%3A%22eyJsYW5nIjoia28ifQ%3D%3D%22%7D\"><i\n");
      out.write("					class=\"fa-brands fa-twitter\" style=\"color: #000000;\"></i></a> <a\n");
      out.write("					href=\"https://www.instagram.com/\"><i\n");
      out.write("					class=\"fa-brands fa-instagram\" style=\"color: #000000;\"></i></a> <a\n");
      out.write("					href=\"https://github.com/login\"><i class=\"fa-brands fa-github\"\n");
      out.write("					style=\"color: #000000;\"></i></a> <a href=\"https://discord.com/login\"><i\n");
      out.write("					class=\"fa-brands fa-discord\" style=\"color: #000000;\"></i></a>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</footer>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("		console.log(registerForm);\n");
      out.write("		if (thereis === \"1\") {\n");
      out.write("			document.getElementById(\"registerForm\").addEventListener(\"submit\", function(e) {\n");
      out.write("		        e.preventDefault();\n");
      out.write("		    });\n");
      out.write("		}\n");
      out.write("	</script>\n");
      out.write("	<script type=\"text/javascript\">\n");
      out.write("    document.getElementById(\"registerForm\").addEventListener(\"submit\", function(e) {\n");
      out.write("        var checkbox = document.querySelector('input[type=\"checkbox\"]');\n");
      out.write("        if (!checkbox.checked) {\n");
      out.write("            e.preventDefault();\n");
      out.write("            alert(\"개인정보 수집에 동의해야 합니다.\");\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("	</script>\n");
      out.write("	<script src=\"/resources/js/HF.js\"></script>\n");
      out.write("	<script src=\"/resources/js/consult/consult.js\"></script>\n");
      out.write("	<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
      out.write("\n");
      out.write("	<script>\n");
      out.write("		var navBar = document.getElementById('nav-bar');\n");
      out.write("		var navBtn = document.getElementById('nav-btn');\n");
      out.write("\n");
      out.write("		navBtn.addEventListener('mouseenter', function() {\n");
      out.write("			navBar.style.width = '300px';\n");
      out.write("		});\n");
      out.write("\n");
      out.write("		navBar.addEventListener('mouseleave', function() {\n");
      out.write("			navBar.style.width = '0';\n");
      out.write("		});\n");
      out.write("	</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/consult/register.jsp(39,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<a href=\"/user/signup\">회원가입</a>\n");
          out.write("								<br>\n");
          out.write("								<a href=\"/user/login\">로그인</a>\n");
          out.write("								<br>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/consult/register.jsp(47,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("								<a href=\"/user/logout\">로그아웃</a>\n");
          out.write("								<br>\n");
          out.write("								<a href=\"/user/modify\">회원수정</a>\n");
          out.write("								<br>\n");
          out.write("								<a href=\"/user/delete\">회원삭제</a>\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
