/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-02 01:18:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.reservation;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admincalender_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\n");
      out.write("<link href='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.css' rel='stylesheet' />\n");
      out.write("<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/main.min.js'></script>\n");
      out.write("<script src='https://cdn.jsdelivr.net/npm/fullcalendar@5.8.0/locales-all.min.js'></script>\n");
      out.write("<link href=\"https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap\" rel=\"stylesheet\">\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/x2js@3.4.4/x2js.min.js\"></script>\n");
      out.write("<script src=\"//cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
      out.write("<script src=\"https://kit.fontawesome.com/e927512ef5.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("	<script\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/reservation/admincalender.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/HF.css\">\n");
      out.write("<title>Admin_calender</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("	<header>\n");
      out.write("		<div class=\"container\">\n");
      out.write("			<div class=\"header\">\n");
      out.write("				<a href=\"/home\"> \n");
      out.write("					<div class=\"logo-title\">\n");
      out.write("						<img src=\"/resources/img/logo2.svg\" alt=\"\">\n");
      out.write("						<h1 class=\"title\" style=\"color: #555;\">OK Rental</h1>\n");
      out.write("					</div>\n");
      out.write("				</a>\n");
      out.write("				<!-- 우측에 위치 -->\n");
      out.write("				<div class=\"header-right\">\n");
      out.write("					<div class=\"info\">\n");
      out.write("						<i class=\"fa-sharp fa-solid fa-user fa-xl\" style=\"color: #555;\"\n");
      out.write("							onclick=\"toggleTooltip();\"></i>\n");
      out.write("						<div id=\"tooltip\" class=\"speech-bubble\">\n");
      out.write("							<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid == null }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("								<a href=\"/user/signup\">회원가입</a>\n");
      out.write("								<br>\n");
      out.write("								<a href=\"/user/login\">로그인</a>\n");
      out.write("								<br>\n");
      out.write("							</c:if>\n");
      out.write("\n");
      out.write("							<!-- 로그인해야 수정 삭제가 보이게 -->\n");
      out.write("							<c:if test=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid != null }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\n");
      out.write("								<a href=\"/user/logout\">로그아웃</a>\n");
      out.write("								<br>\n");
      out.write("								<a href=\"/user/modify\">회원수정</a>\n");
      out.write("								<br>\n");
      out.write("								<a href=\"/user/delete\">회원삭제</a>\n");
      out.write("								<br>\n");
      out.write("								<a href=\"/consult/register\">상담신청</a>\n");
      out.write("								\n");
      out.write("							</c:if>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("					<!-- 230710 서치 -->\n");
      out.write("					<div class=\"search\">\n");
      out.write("						<span id=\"search\"> <i\n");
      out.write("							class=\"fa-solid fa-magnifying-glass fa-xl\" style=\"color: #555;\"></i>\n");
      out.write("						</span>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div id=\"myOverlay\" class=\"overlay\">\n");
      out.write("			<span class=\"closebtn\" onclick=\"closeSearch()\" title=\"Close Overlay\">×</span>\n");
      out.write("			<div class=\"overlay-content\">\n");
      out.write("				<form action=\"/product/search\" method=\"get\">\n");
      out.write("					<div class=\"search-container\">\n");
      out.write("						<h1 style=\"color: white;\">Quickly Search Site</h1>							\n");
      out.write("						<div class=\"search-box\">\n");
      out.write("							<input type=\"text\" placeholder=\"Search..\" name=\"search\"\n");
      out.write("									class=\"search-input\">\n");
      out.write("							<button type=\"submit\" style=\"color: #555;\">Search</button>\n");
      out.write("						</div>	\n");
      out.write("					</div>\n");
      out.write("				</form>\n");
      out.write("				<div class=\"quickly\">\n");
      out.write("					<ul>\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=다이슨\"> dyson</a></li>\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=엘지\"> lg </a></li>\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=쿠쿠\"> cuckoo </a></li>\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=코웨이\"> coway </a></li>\n");
      out.write("					</ul>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div id=\"blurryPart\" class=\"blurry-part\"></div>\n");
      out.write("		<!-- 230710 서치 -->\n");
      out.write("		\n");
      out.write("		\n");
      out.write("	\n");
      out.write("\n");
      out.write("	</header>\n");
      out.write("	<h1 style=\"text-align: center; margin-top: 64px !important;\">Admin_calender</h1>\n");
      out.write("\n");
      out.write("	<div id='wrap'>\n");
      out.write("		<div class=\"button-container\">\n");
      out.write("			<button id='save' class=\"apple-style-button\">save</button>\n");
      out.write("		</div>\n");
      out.write("\n");
      out.write("		<div id='calendar-wrap'>\n");
      out.write("			<div id='calendar1'></div>\n");
      out.write("		</div>\n");
      out.write("	</div>\n");
      out.write("	<script src=\"/resources/js/HF.js\"></script>\n");
      out.write("	<script src=\"/resources/js/reservation/admincalender.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
