/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-03 02:06:11 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/_spring_workspace/ezen_project/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/spring/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1687741574536L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>home</title>\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/e927512ef5.js\"\r\n");
      out.write("	crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js\"></script>\r\n");
      out.write("<link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("<link\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap\"\r\n");
      out.write("	rel=\"stylesheet\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://unpkg.com/swiper@8/swiper-bundle.min.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/home.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/slide.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/resources/css/chat/chatbot.css\">\r\n");
      out.write("<script src=\"/resources/js/chat/chatForm.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("<body style=\"scroll-padding-bottom: 100px;\">\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"header\">\r\n");
      out.write("				<a href=\"/home\"> \r\n");
      out.write("					<div class=\"logo-title\">\r\n");
      out.write("						<img src=\"/resources/img/logo2.svg\" alt=\"\">\r\n");
      out.write("						<h1 class=\"title\" style=\"color: #555;\">OK Rental</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("				</a>\r\n");
      out.write("				<!-- 우측에 위치 -->\r\n");
      out.write("				<div class=\"header-right\">\r\n");
      out.write("					<div class=\"info\">\r\n");
      out.write("						<i class=\"fa-sharp fa-solid fa-user fa-xl\" style=\"color: #555;\"\r\n");
      out.write("							onclick=\"toggleTooltip();\"></i>\r\n");
      out.write("						<div id=\"tooltip\" class=\"speech-bubble\">\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<!-- 로그인해야 수정 삭제가 보이게 -->\r\n");
      out.write("							");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- 230710 서치 -->\r\n");
      out.write("					<div class=\"search\">\r\n");
      out.write("						<span id=\"search\"> <i\r\n");
      out.write("							class=\"fa-solid fa-magnifying-glass fa-xl\" style=\"color: #555;\"></i>\r\n");
      out.write("						</span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id=\"myOverlay\" class=\"overlay\">\r\n");
      out.write("			<span class=\"closebtn\" onclick=\"closeSearch()\" title=\"Close Overlay\">×</span>\r\n");
      out.write("			<div class=\"overlay-content\">\r\n");
      out.write("				<form action=\"/product/search\" method=\"get\">\r\n");
      out.write("					<div class=\"search-container\">\r\n");
      out.write("						<h1 style=\"color: white;\">Quickly Search Site</h1>							\r\n");
      out.write("						<div class=\"search-box\">\r\n");
      out.write("							<input type=\"text\" placeholder=\"Search..\" name=\"search\"\r\n");
      out.write("									class=\"search-input\">\r\n");
      out.write("							<button type=\"submit\" style=\"color: #555;\">Search</button>\r\n");
      out.write("						</div>	\r\n");
      out.write("					</div>\r\n");
      out.write("				</form>\r\n");
      out.write("				<div class=\"quickly\">\r\n");
      out.write("					<ul>\r\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\r\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=다이슨\"> dyson</a></li>\r\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\r\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=엘지\"> lg </a></li>\r\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\r\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=쿠쿠\"> cuckoo </a></li>\r\n");
      out.write("						<li><i class=\"fa-solid fa-arrow-right fa-xs\"\r\n");
      out.write("							style=\"color: #ffffff;\"></i> <a href=\"/product/search?search=코웨이\"> coway </a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div id=\"blurryPart\" class=\"blurry-part\"></div>\r\n");
      out.write("		<!-- 230710 서치 -->\r\n");
      out.write("		\r\n");
      out.write("		<!-- id container는 화면 중앙 상단에 위치  -->\r\n");
      out.write("		<div class=\"nav\">\r\n");
      out.write("			<div class=\"center-items\">\r\n");
      out.write("				<a href=\"/product/list?type_a=정수기\"><p>Water purifier</p></a> \r\n");
      out.write("				<a href=\"/product/list?type_a=공기청정기\"><p>Air purifier</p></a> \r\n");
      out.write("				<a href=\"/product/list?type_a=제습기\"><p>Dehumidifier</p></a> \r\n");
      out.write("				<a href=\"/product/list?type_a=에어컨\"><p>Air Conditioner</p></a>\r\n");
      out.write("				<a href=\"/product/list?type_a=텔레비전\"><p>Television</p></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<br>\r\n");
      out.write("		<!-- 호버메뉴 -->\r\n");
      out.write("		<div class=\"nav-btn\" id=\"nav-btn\">☰</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"nav-bar\" id=\"nav-bar\">\r\n");
      out.write("			<a href=\"/reservation/calender\">예약신청</a> <a href=\"/consult/register\">상담신청</a>\r\n");
      out.write("			<a href=\"/consult/csCenter\">고객센터</a>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("	<!-- 영상orCF광고 -->\r\n");
      out.write("	<main>\r\n");
      out.write("		<div class=\"video-box\">\r\n");
      out.write("			<video src=\"/resources/video/도시.mp4\" muted autoplay loop>\r\n");
      out.write("				<source src=\"/resources/video/도시.mp4\" type=\"video/mp4\">\r\n");
      out.write("			</video>\r\n");
      out.write("		</div>\r\n");
      out.write("	</main>\r\n");
      out.write("\r\n");
      out.write("	<!-- 이제부터 그냥 홈페이지 -->\r\n");
      out.write("\r\n");
      out.write("	<!-- ************************************* -->\r\n");
      out.write("\r\n");
      out.write("	<section id=\"tranding\">\r\n");
      out.write("		<div class=\"container2\">\r\n");
      out.write("			<h3 class=\"text-center section-subheading\">- popular products -</h3>\r\n");
      out.write("			<h1 class=\"text-center section-heading\">Tranding products</h1>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"container2\">\r\n");
      out.write("			<div class=\"swiper tranding-slider\">\r\n");
      out.write("				<div class=\"swiper-wrapper\">\r\n");
      out.write("					<!-- Slide-start -->\r\n");
      out.write("					<div class=\"swiper-slide tranding-slide\">\r\n");
      out.write("						<div class=\"tranding-slide-img\">\r\n");
      out.write("							<img src=\"/resources/img/정수기.jpg\" alt=\"Tranding\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"tranding-slide-content\">\r\n");
      out.write("							<h1 class=\"food-price\">₩ 1,040,000</h1>\r\n");
      out.write("							<div class=\"tranding-slide-content-bottom\">\r\n");
      out.write("								<h2 class=\"food-name\">water purifier</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Slide-end -->\r\n");
      out.write("					<!-- Slide-start -->\r\n");
      out.write("					<div class=\"swiper-slide tranding-slide\">\r\n");
      out.write("						<div class=\"tranding-slide-img\">\r\n");
      out.write("							<img src=\"/resources/img/공기청정기.jpg\" alt=\"Tranding\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"tranding-slide-content\">\r\n");
      out.write("							<h1 class=\"food-price\">₩ 547,710</h1>\r\n");
      out.write("							<div class=\"tranding-slide-content-bottom\">\r\n");
      out.write("								<h2 class=\"food-name\" style=\"color: white;\">air purifier</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Slide-end -->\r\n");
      out.write("					<!-- Slide-start -->\r\n");
      out.write("					<div class=\"swiper-slide tranding-slide\">\r\n");
      out.write("						<div class=\"tranding-slide-img\">\r\n");
      out.write("							<img src=\"/resources/img/매트리스.jpg\" alt=\"Tranding\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"tranding-slide-content\">\r\n");
      out.write("							<h1 class=\"food-price\">₩ 498,000</h1>\r\n");
      out.write("							<div class=\"tranding-slide-content-bottom\">\r\n");
      out.write("								<h2 class=\"food-name\" style=\"color: white;\">mattress</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Slide-end -->\r\n");
      out.write("					<!-- Slide-start -->\r\n");
      out.write("					<div class=\"swiper-slide tranding-slide\">\r\n");
      out.write("						<div class=\"tranding-slide-img\">\r\n");
      out.write("							<img src=\"/resources/img/식기세척기.jpg\" alt=\"Tranding\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"tranding-slide-content\">\r\n");
      out.write("							<h1 class=\"food-price\">₩ 1,070,550</h1>\r\n");
      out.write("							<div class=\"tranding-slide-content-bottom\">\r\n");
      out.write("								<h2 class=\"food-name\" style=\"color: white;\">dishwasher</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Slide-end -->\r\n");
      out.write("					<!-- Slide-start -->\r\n");
      out.write("					<div class=\"swiper-slide tranding-slide\">\r\n");
      out.write("						<div class=\"tranding-slide-img\">\r\n");
      out.write("							<img src=\"/resources/img/무선청소기.jpg\" alt=\"Tranding\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"tranding-slide-content\">\r\n");
      out.write("							<h1 class=\"food-price\">₩ 990,000</h1>\r\n");
      out.write("							<div class=\"tranding-slide-content-bottom\">\r\n");
      out.write("								<h2 class=\"food-name\" style=\"color: white;\">wireless vacuum\r\n");
      out.write("									cleaner</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Slide-end -->\r\n");
      out.write("					<!-- Slide-start -->\r\n");
      out.write("					<div class=\"swiper-slide tranding-slide\">\r\n");
      out.write("						<div class=\"tranding-slide-img\">\r\n");
      out.write("							<img src=\"/resources/img/로봇청소기.jpg\" alt=\"Tranding\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"tranding-slide-content\">\r\n");
      out.write("							<h1 class=\"food-price\">₩ 2,306,000</h1>\r\n");
      out.write("							<div class=\"tranding-slide-content-bottom\">\r\n");
      out.write("								<h2 class=\"food-name\" style=\"color: white;\">robot vacuum\r\n");
      out.write("									cleaner</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Slide-end -->\r\n");
      out.write("					<!-- Slide-start -->\r\n");
      out.write("					<div class=\"swiper-slide tranding-slide\">\r\n");
      out.write("						<div class=\"tranding-slide-img\">\r\n");
      out.write("							<img src=\"/resources/img/밥솥.jpg\" alt=\"Tranding\">\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"tranding-slide-content\">\r\n");
      out.write("							<h1 class=\"food-price\">₩ 508,630</h1>\r\n");
      out.write("							<div class=\"tranding-slide-content-bottom\">\r\n");
      out.write("								<h2 class=\"food-name\" style=\"color: white;\">Rice cooker</h2>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<!-- Slide-end -->\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"tranding-slider-control\">\r\n");
      out.write("					<div class=\"swiper-button-prev slider-arrow\">\r\n");
      out.write("						<ion-icon name=\"arrow-back-outline\"></ion-icon>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"swiper-button-next slider-arrow\">\r\n");
      out.write("						<ion-icon name=\"arrow-forward-outline\"></ion-icon>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"swiper-pagination\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<!-- ************************************* -->\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		<!-- 230706 -->\r\n");
      out.write("		<div class=\"section2\">\r\n");
      out.write("			<h1 style=\"color: #555;\">Time Sale D-day</h1>\r\n");
      out.write("			<video src=\"/resources/video/티비CF.webm\" muted autoplay loop></video>\r\n");
      out.write("			<div class=\"cnt\">\r\n");
      out.write("				<div id=\"days\" class=\"countdown animated\"></div>\r\n");
      out.write("				<div id=\"hours\" class=\"countdown animated\"></div>\r\n");
      out.write("				<div id=\"minutes\" class=\"countdown animated\"></div>\r\n");
      out.write("				<div id=\"seconds\" class=\"countdown animated\"></div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<article>\r\n");
      out.write("         <div class=\"section1\">\r\n");
      out.write("            <div class=\"inner\">\r\n");
      out.write("               <div class=\"title_area\">\r\n");
      out.write("                  <h2>Customer Rental Services</h2>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"desc\">\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <a href=\"https://www.cuckoo.co.kr/customer/customerDirectRentalAuth?rentalType=NewInstall\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                           <img src=\"/resources/img/달력.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon_tit\">신규 설치일정 조회/변경</div>\r\n");
      out.write("                        <div class=\"link\">\r\n");
      out.write("                           <span> 바로가기</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <a href=\"https://www.cuckoo.co.kr/customer/customerDirectRentalAuth?rentalType=Transfer\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                           <img src=\"/resources/img/셋팅.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon_tit\">이전설치 신청/조회</div>\r\n");
      out.write("                        <div class=\"link\">\r\n");
      out.write("                           <span>바로가기</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <a href=\"https://www.cuckoo.co.kr/customer/customerDirectRentalAuth?rentalType=Remain\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                           <img src=\"/resources/img/머니.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon_tit\">렌탈료/만료일 잔여 조회</div>\r\n");
      out.write("                        <div class=\"link\">\r\n");
      out.write("                           <span>바로가기</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <a href=\"https://www.cuckoo.co.kr/customer/customerDirectRentalAuth?rentalType=NonPayment\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                           <img src=\"/resources/img/요금.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon_tit\">미납요금 조회/결제</div>\r\n");
      out.write("                        <div class=\"link\">\r\n");
      out.write("                           <span>바로가기</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <a href=\"https://www.cuckoo.co.kr/customer/customerDirectRentalAuth?rentalType=ChangeCard\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                           <img src=\"/resources/img/요금변경.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon_tit\">결제 카드 변경</div>\r\n");
      out.write("                        <div class=\"link\">\r\n");
      out.write("                           <span>바로가기</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <a href=\"https://www.cuckoo.co.kr/customer/customerDirectRentalAuth?rentalType=Deposit\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                           <img src=\"/resources/img/입금확인.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon_tit\">입금 확인증 조회</div>\r\n");
      out.write("                        <div class=\"link\">\r\n");
      out.write("                           <span>바로가기</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <a href=\"https://www.cuckoo.co.kr/customer/tag/customerSelfItemSearch?tagNo=8\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                           <img src=\"/resources/img/동영상조회.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon_tit\">동영상 조회</div>\r\n");
      out.write("                        <div class=\"link\">\r\n");
      out.write("                           <span>바로가기</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div>\r\n");
      out.write("                     <a href=\"/user/login\">\r\n");
      out.write("                        <div class=\"icon\">\r\n");
      out.write("                           <img src=\"/resources/img/포인트조회.png\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"icon_tit\">렌탈료 포인트 납부</div>\r\n");
      out.write("                        <div class=\"link\">\r\n");
      out.write("                           <span>바로가기</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                     </a>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("         </div>\r\n");
      out.write("      </article>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- 플로팅 메뉴 or 퀵메뉴 -->\r\n");
      out.write("   <div class=\"floating\">\r\n");
      out.write("      <button id=\"info-button\">\r\n");
      out.write("         <i class=\"fa-solid fa-question\" style=\"color: white;\"></i>\r\n");
      out.write("      </button>\r\n");
      out.write("      <div id=\"info-modal\" class=\"modal\">\r\n");
      out.write("         <div id=\"modal-header\" style=\"display: flex; justify-content: center; align-items: center;\">\r\n");
      out.write("            <img class=\"robot-icon2\" alt=\"robot-icon\" src=\"/resources/img/icon_robot.png\" />\r\n");
      out.write("            <span>챗봇 서비스</span>        \r\n");
      out.write("            <span id=\"close-button\">&times;</span>\r\n");
      out.write("         </div>      \r\n");
      out.write("         <div id=\"wrap\">                 \r\n");
      out.write("             <!-- 응답 메시지 출력  -->\r\n");
      out.write("             <div id=\"chatBox\"></div>\r\n");
      out.write("\r\n");
      out.write("             <!-- 질문 메시지 입력 폼 -->\r\n");
      out.write("             <form id=\"chatForm\" style=\"display: flex; border: none; width: 100%\" >\r\n");
      out.write("                  <input type=\"text\" id=\"message\" name=\"message\" size=\"30\" placeholder=\"질문을 입력하세요\">\r\n");
      out.write("                  <input type=\"submit\" value=\"전송\">\r\n");
      out.write("             </form>\r\n");
      out.write("             \r\n");
      out.write("          </div>\r\n");
      out.write("      </div>   \r\n");
      out.write("   </div>\r\n");
      out.write("\r\n");
      out.write("	<!-- 관리자만 보이는 버튼 좌측 하단에 작게 표시 마우스 호버있음 -->\r\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footer\">\r\n");
      out.write("			<div class=\"ft-logo\">\r\n");
      out.write("				<img src=\"/resources/img/logo2.svg\" alt=\"\" width=\"50px\"\r\n");
      out.write("					height=\"50px\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"footinfo\">\r\n");
      out.write("				<h6>©2023 Ok RENTAL. All Rights Reserved.</h6>\r\n");
      out.write("				<a href=\"#\"><h6>RETURN POLICY</h6></a> <a href=\"#\"><h6>TERMS\r\n");
      out.write("						& LEGAL</h6></a> <a href=\"#\"><h6>PRIVACY NOTICE</h6></a>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"footsns\">\r\n");
      out.write("				<a href=\"https://www.facebook.com/login/?locale=ko_KR\"><i\r\n");
      out.write("					class=\"fa-brands fa-facebook\" style=\"color: #000000;\"></i></a> <a\r\n");
      out.write("					href=\"https://twitter.com/i/flow/login?input_flow_data=%7B%22requested_variant%22%3A%22eyJsYW5nIjoia28ifQ%3D%3D%22%7D\"><i\r\n");
      out.write("					class=\"fa-brands fa-twitter\" style=\"color: #000000;\"></i></a> <a\r\n");
      out.write("					href=\"https://www.instagram.com/\"><i\r\n");
      out.write("					class=\"fa-brands fa-instagram\" style=\"color: #000000;\"></i></a> <a\r\n");
      out.write("					href=\"https://github.com/login\"><i class=\"fa-brands fa-github\"\r\n");
      out.write("					style=\"color: #000000;\"></i></a> <a href=\"https://discord.com/login\"><i\r\n");
      out.write("					class=\"fa-brands fa-discord\" style=\"color: #000000;\"></i></a>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("	<script src=\"/resources/js/home.js\"></script>\r\n");
      out.write("	<!-- ************************************************* -->\r\n");
      out.write("	<script type=\"module\"\r\n");
      out.write("		src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>\r\n");
      out.write("	<script nomodule\r\n");
      out.write("		src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js\"></script>\r\n");
      out.write("	<script src=\"https://unpkg.com/swiper@8/swiper-bundle.min.js\"></script>\r\n");
      out.write("	<script type=\"module\"\r\n");
      out.write("		src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>\r\n");
      out.write("	<script nomodule\r\n");
      out.write("		src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js\"></script>\r\n");
      out.write("	<script src=\"https://unpkg.com/swiper@8/swiper-bundle.min.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("		var TrandingSlider = new Swiper('.tranding-slider', {\r\n");
      out.write("			effect : 'coverflow',\r\n");
      out.write("			grabCursor : true,\r\n");
      out.write("			centeredSlides : true,\r\n");
      out.write("			loop : true,\r\n");
      out.write("			slidesPerView : 'auto',\r\n");
      out.write("			coverflowEffect : {\r\n");
      out.write("				rotate : 0,\r\n");
      out.write("				stretch : 0,\r\n");
      out.write("				depth : 100,\r\n");
      out.write("				modifier : 2.5,\r\n");
      out.write("			},\r\n");
      out.write("			pagination : {\r\n");
      out.write("				el : '.swiper-pagination',\r\n");
      out.write("				clickable : true,\r\n");
      out.write("			},\r\n");
      out.write("			navigation : {\r\n");
      out.write("				nextEl : '.swiper-button-next',\r\n");
      out.write("				prevEl : '.swiper-button-prev',\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("         const modifySus = '");
      if (_jspx_meth_c_005fout_005f0(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("         console.log(modifySus); \r\n");
      out.write("         if(modifySus == 2){\r\n");
      out.write("          alert(\"회원정보가 수정되었습니다\")   \r\n");
      out.write("         }\r\n");
      out.write("         const signupFail = '");
      if (_jspx_meth_c_005fout_005f1(_jspx_page_context))
        return;
      out.write("';\r\n");
      out.write("         console.log(\"dddddd \"+signupFail);\r\n");
      out.write("         if(signupFail == 2){\r\n");
      out.write("            alert('회원가입되었습니다. 로그인해주세요~!');\r\n");
      out.write("         }\r\n");
      out.write("   </script> \r\n");
      out.write("   <script>\r\n");
      out.write("     document.addEventListener('DOMContentLoaded', function () {\r\n");
      out.write("       // 해당 버튼 요소를 가져옴\r\n");
      out.write("       const adminButton = document.getElementById('nav-bar');\r\n");
      out.write("   \r\n");
      out.write("       // 버튼을 클릭할 때의 이벤트 리스너 등록\r\n");
      out.write("       adminButton.addEventListener('click', function (event) {\r\n");
      out.write("         // 세션에서 가져온 isLoggedIn 값을 읽음\r\n");
      out.write("          const isLoggedIn = ");
      if (_jspx_meth_c_005fout_005f2(_jspx_page_context))
        return;
      out.write(";\r\n");
      out.write("            if (!isLoggedIn) {\r\n");
      out.write("              event.preventDefault(); // 버튼의 기본 동작을 막음 (링크를 클릭해도 이동하지 않음)\r\n");
      out.write("              alert('로그인 후 이용 가능합니다.');\r\n");
      out.write("            }\r\n");
      out.write("       });\r\n");
      out.write("     });\r\n");
      out.write("   </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(44,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid == null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<a href=\"/user/signup\">회원가입</a>\r\n");
          out.write("								<br>\r\n");
          out.write("								<a href=\"/user/login\">로그인</a>\r\n");
          out.write("								<br>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(52,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<a href=\"/user/logout\">로그아웃</a>\r\n");
          out.write("								<br>\r\n");
          out.write("								<a href=\"/user/modify\">회원수정</a>\r\n");
          out.write("								<br>\r\n");
          out.write("								<a href=\"/user/delete\">회원삭제</a>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/home.jsp(396,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.cid eq 'admin' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		<div class=\"floating-admin\">\r\n");
          out.write("			<button id=\"admin-button-left\">\r\n");
          out.write("				<i class=\"fa-solid fa-cogs\" style=\"color: white;\"></i>\r\n");
          out.write("			</button>\r\n");
          out.write("		</div>\r\n");
          out.write("\r\n");
          out.write("		<div id=\"admin-modal-left\" class=\"modal-left\">\r\n");
          out.write("			<div class=\"modal-content-left\">\r\n");
          out.write("				<span id=\"close-button-admin-left\">&times;</span>\r\n");
          out.write("				<div class=\"modal-buttons-left\">\r\n");
          out.write("					<a href=\"/product/register\"><button class=\"modal-btn-left\">상품등록</button></a>\r\n");
          out.write("					<a href=\"/product/adminList\"><button class=\"modal-btn-left\">상품전체리스트</button></a>\r\n");
          out.write("					<a href=\"/consult/adminList\"><button class=\"modal-btn-left\">상담신청목록</button></a>\r\n");
          out.write("					<a href=\"/reservation/admincalender\"><button class=\"modal-btn-left\">예약현황</button></a>\r\n");
          out.write("				</div>\r\n");
          out.write("			</div>\r\n");
          out.write("		</div>\r\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(475,28) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${modifyFail}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(480,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${signupFail}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f2 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f2_reused = false;
    try {
      _jspx_th_c_005fout_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f2.setParent(null);
      // /WEB-INF/views/home.jsp(494,29) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses != null}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f2 = _jspx_th_c_005fout_005f2.doStartTag();
      if (_jspx_th_c_005fout_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f2);
      _jspx_th_c_005fout_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f2_reused);
    }
    return false;
  }
}
